[package]
name = "bidirectional"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
drasi-server-core = { path = "../../" }
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
serde_json = "1.0"
