[package]
name = "drasi-functions-cypher"
version = "0.3.4"
edition = "2021"
license = "Apache-2.0"
description = "Cypher function implementations for Drasi"
repository = "https://github.com/drasi-project/drasi-core"

[lints]
workspace = true

[dependencies]
drasi-core.workspace = true
