[package]
name = "shared-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
drasi-query-ast = { path = "../drasi-query-ast" }
drasi-query-core = { path = "../drasi-query-core" }
drasi-query-cypher = { path = "../drasi-query-cypher" }
drasi-query-middleware = { path = "../drasi-query-middleware" }
serde = "1.0.163"
serde_json = "1.0.96"
async-trait = "0.1.68"
tokio = { version = "1.6", features = ["full"] }
env_logger = "0.10.0"
log = "0.4"
futures = "0.3.28"
chrono = "0.4.31"
