[package]
name = "drasi-functions-gql"
version.workspace = true
edition = "2021"

[lints]
workspace = true

[dependencies]
drasi-core = { version = "0.1.0", path = "../core" }

[dev-dependencies]
tokio = { version = "1.29.1", features = ["full"] }